service: lk-stock-market-backend-fetch
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

custom:
  webpack:
    webpackConfig: ../../webpack.config.cjs # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    # excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
    
package:
  individually: true

functions:
  fetchMarketDataFromStockMarket:
    handler: index.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  # cronHandler:
  #   handler: index.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0/2 * ? * MON-FRI *)

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-local-schedule
