service: lk-stock-market
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  region: ap-south-1
  architecture: arm64
  memorySize: 512 # optional, in MB, default is 1024
  runtime: nodejs18.x
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true

custom:
  webpack:
    webpackConfig: ../../webpack.config.cjs # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    # excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

package:
  individually: true

functions:
  fetchStockDataAndUpdate:
    handler: index.run
    events:
      - schedule: cron(10 10-13 * * 1-5) # Invoke Lambda function Mon to fry from 10 to 13, eg: 10.10, 11.10, 12.10
      # - schedule: rate(6 hours)

    environment:
      S3_BUCKET: ${env:S3_BUCKET}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-local-schedule
